name: "NeuroData Docs"
markdown: kramdown
highlighter: pygments
permalink: /:title/

baseurl: /nddocs
url: http://docs.neurodata.io/

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME


defaults:
    values:
      layout: "default"
