name: "NeuroData Docs"
markdown: kramdown
highlighter: rouge
permalink: /:title.html

baseurl: /nddocs
url: http://docs.neurodata.io

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-redirect-from # redirects 

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
